language: ruby
cache: bundler
rvm:
  - 2.4.1
jdk:
  - oraclejdk8
script:
  - bundle exec rake spec rubocop
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "RAILS_ENV=test bundle exec rake db:setup"
branches:
 only:
    - master
addons:
 postgresql: "9.4"
services:
  - postgresql
notifications:
  webhooks: http://travis-hook.wize.studio
