default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  username: postgres

development:
  <<: *default
  database: <%= [Rails.application.class.parent_name.underscore,'development'].join('_') %>
  host: localhost

test:
  <<: *default
  database: <%= [Rails.application.class.parent_name.underscore,'test'].join('_') %>

production:
  <<: *default
  database: <%= [Rails.application.class.parent_name.underscore,'production'].join('_') %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
